MODEL:
        #PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_CHOICE: 'self'
  PRETRAIN_PATH: '/home/ubuntu/jenni/ckpts/mm/rgbnt100/hpo/seed_1236/vit_rnt_no_fusion_s128x256_bs_256_lr_.016_120.pth'
  #PRETRAIN_PATH: '/home/ubuntu/jenni/jx_vit_base_p16_224-80ecf9dd.pth'  
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('2')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [12, 12]
  CLS_TOKEN_NUM: 1
  CLS_TOKENS_LOSS: False
  JPM: False
  SIE_CAMERA: False
  SIE_COE: 3.0
  METRIC_LOSS_TYPE: 'ce_triplet'
  DEPTH: 12
<<<<<<< Updated upstream
  USE_FUSION: True
  FUSION_METHOD: 'cat'
=======
  USE_FUSION: False
  FUSION_METHOD: 'av'
>>>>>>> Stashed changes
  LATE_FUSION: True
  EMBED_DIM: 768
  SAME_MODEL: False

INPUT:
  SIZE_TRAIN: [128, 256]
  SIZE_TEST: [128, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  GS_PROB: 1.0 
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ['rgbnt100__rnt']
  ROOT_DIR: ['/data/datasets/research-datasets/reid_mm/RGBNT100']

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 60
  BASE_LR: .008
  IMS_PER_BATCH: 256
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 61
  LOG_PERIOD: 5
  EVAL_PERIOD: 5
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
<<<<<<< Updated upstream
  SEED: 1236
=======
  SEED: 1235
>>>>>>> Stashed changes
  DISCRIM_LR: 1e-4
  DISCRIM_DELAY: 0

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
<<<<<<< Updated upstream
  WEIGHT: '/home/ubuntu/jenni/ckpts/mm/rgbnt100/hpo/seed_1236/vit_rnt_fusion_cat_s128x256_bs_256_lr_.016_120.pth'
  NECK_FEAT: 'after' 
=======
  WEIGHT: '/home/ubuntu/jenni/ckpts/mm/rgbnt100/hpo/seed_1236/vit_rnt_no_fusion_s128x256_bs_256_lr_.016_120.pth'
  NECK_FEAT: 'before'
>>>>>>> Stashed changes
  FEAT_NORM: 'yes'
  AVERAGE_GAL: False
OUTPUT_DIR: '../logs/mm/rgbnt100/vit_rnt_no_pretrain_no_fusion'
CKPT_DIR: '/home/ubuntu/jenni/ckpts/mm/rgbnt100/vit_rnt_no_pretrain_no_fusion'

